name: update main branch

on:
  push:
    branches:
      - main 

env:
  github_token: ${{ secrets.PAT_TOKEN }}

jobs:
  copy_branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
      
      - name: Update branch in repo
        run: |
          git config --global user.email "ghost8658@gmail.com"
          git config --global user.name "ghost8658"
          git checkout main
          git remote remove origin
          git remote add origin https://github.com/ghost8658private/ttesting.git
          git config pull.rebase false 
          git pull origin main --allow-unrelated-histories
          ls

    #   - name: Commit and Push Changes
    #     run: |
    #         git add .
    #         git commit -m "Update main branch"
    #         git push origin main
