name: Push Changes from Upstream

on:
  push:
    branches:
      - main

jobs:
  pushChanges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git Credentials
        run: |
            git config --global user.email "Ghost8658@gmail.com"
            git config --global user.name "Ghost8658"

      - name: Set Upstream Repo URL
        run: |
          UPSTREAM_REPO=https://github.com/ghost8658private/ttesting.git
          BRANCHES=main:main
          git remote set-url origin $UPSTREAM_REPO
          git fetch $UPSTREAM_REPO main

      - name: Merge Upstream Changes
        run: |
          git checkout main
          # git merge $UPSTREAM_REPO/main --allow-unrelated-histories

      - name: Push Changes
        run: |
          # Configure SSH key for authentication
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Push using SSH
          # git pull $UPSTREAM_REPO
          git push origin main

      - name: Clean Up
        run: |
          git remote rm $UPSTREAM_REPO
