name: Sync Upstream to Main

on:
  workflow_call:
    inputs:
      upstream-repo:
        required: true
        type: string
      main-repo:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  synchronize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git Credentials
        run: |
          git config --global user.email "Ghost8658@gmail.com"
          git config --global user.name "Ghost8658"

      - name: Add Upstream Remote
        run: |
          git remote add upstream ${{ inputs.upstream-repo }}

      - name: Fetch Upstream Changes
        run: |
          git fetch upstream

      - name: Push Upstream Changes to Main Repo
        run: |
          git push ${{ inputs.main-repo }} HEAD:main

