name: Push Changes from Upstream

on:
  push:
    branches:
      - main

jobs:
  pushChanges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Upstream Repo URL
        run: |
          UPSTREAM_REPO=https://github.com/ghost8658private/ttesting.git
          BRANCHES=main:main
          git remote add tmp_upstream $UPSTREAM_REPO
          git fetch tmp_upstream main

      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge tmp_upstream/main --allow-unrelated-histories

      - name: Push Changes
        run: |
          git push origin tmp_upstream/main:main

      - name: Clean Up
        run: |
          git remote rm tmp_upstream
