name: Sync Upstream to Main

on:
  workflow_call:
    inputs:
      upstream-repo:
        required: true
        type: string
      main-repo:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true
      SSH_KEY:
        required: true

jobs:
  synchronize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    

      - name: Add SSH key
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p /home/runner/.ssh
            ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
            # SSH_KEY is the name of the repository secret
            echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/id_rsa 
            chmod 600 /home/runner/.ssh/id_rsa 
            chmod 700 /home/runner/.ssh
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
            ssh-add /home/runner/.ssh/id_rsa 


      - name: Set Git Credentials
        run: |
          git config --global user.email "bbbeeeaaabbb9@gmail.com"
          git config --global user.name "ghost8658private"

      - name: Add Upstream Remote
        run: |
          git remote set-url origin git@github.com:${{ inputs.main-repo }}
          git remote add upstream git@github.com:${{ inputs.upstream-repo }}

      - name: Fetch Upstream Changes
        run: |
          git fetch upstream main
          git gc --prune=now

      - name: Push Upstream Changes to Main Repo
        run: |
          #ssh -vT git@github.com
          #ssh -T git@github.com
          
          git config pull.rebase false
          git pull upstream main --allow-unrelated-histories
          ls
          git checkout -b maine
          git pull origin main --allow-unrelated-histories 
          ls
          git push git@github.com:${{ inputs.main-repo }}